

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!


target 'AXSwiftKit_Example' do
  pod 'AXSwiftKit', :path => '../'
  # 网络请求AFN swift版本
  pod 'Alamofire'
  
  pod 'SnapKit', '~> 5.0.0'
  
  pod 'ReactiveSwift', '~> 6.1'
  pod 'ReactiveCocoa', '~> 10.1'
  
  # JSON 连续取值
  pod 'SwiftyJSON', '~> 4.0'
  # json > model
  pod 'ObjectMapper'
  
  # 测试工具
#  pod 'MLeaksFinder'
#  pod 'LookinServer', :configurations => ['Debug']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
