# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

#source 'https://cdn.cocoapods.org/'
workspace 'AXSwiftKitExample.xcworkspace'

target 'AXSwiftKitExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'AXSwiftKit', :path => '../'
  
  # 网络请求AFN swift版本
  pod 'Alamofire'
  
  target 'AXSwiftKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'AXSwiftKitExampleUITests' do
    # Pods for testing
  end
  
end


#AXSwiftKit 依赖
target 'AXSwiftKit' do
  
  project '../AXSwiftKit.xcodeproj'
  
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
